var searchData=
[
  ['technicalities_20for_20developers_0',['Technicalities for Developers',['../md_extra__doc_22__technicalities.html',1,'']]],
  ['terminating_20sensitive_20volumes_20for_20photon_20tracking_1',['Non-terminating sensitive volumes for photon tracking',['../md_extra__doc_20__common.html#autotoc_md19',1,'']]],
  ['tessellatedmesh_2',['TessellatedMesh',['../class_c_a_d_mesh_1_1_tessellated_mesh.html',1,'CADMesh']]],
  ['the_20output_3',['2. Analyse the Output',['../md_extra__doc_21__multithreading.html#autotoc_md30',1,'']]],
  ['the_20tools_20namespace_4',['The Tools namespace',['../md_extra__doc_22__technicalities.html#autotoc_md34',1,'']]],
  ['thread_5',['Example: Saving Data Per Thread',['../md_extra__doc_21__multithreading.html#autotoc_md26',1,'']]],
  ['thread_20safe_20containers_6',['Best Practices for Creating New Thread-Safe Containers',['../md_extra__doc_21__multithreading.html#autotoc_md27',1,'']]],
  ['thread_20safe_20global_20instance_20implementation_7',['Thread-Safe Global Instance Implementation',['../md_extra__doc_21__multithreading.html#autotoc_md24',1,'']]],
  ['thread_20safety_20guidelines_8',['Thread Safety Guidelines',['../md_extra__doc_21__multithreading.html#autotoc_md23',1,'']]],
  ['threading_20issues_9',['Troubleshooting Multi-threading Issues',['../md_extra__doc_21__multithreading.html#autotoc_md28',1,'']]],
  ['threading_20mode_10',['Multi-threading mode',['../md_extra__doc_21__multithreading.html',1,'']]],
  ['threadlocaldata_11',['ThreadLocalData',['../struct_o_m_sim_hit_manager_1_1_thread_local_data.html',1,'OMSimHitManager']]],
  ['time_20and_20detection_20probability_12',['PMTs Charge, transit time and detection probability',['../md_extra__doc_20__common.html#autotoc_md15',1,'']]],
  ['time_20scans_13',['Step 4: Matching gain / transit time scans',['../md_extra__doc_22__technicalities.html#autotoc_md42',1,'']]],
  ['to_20effective_20areas_14',['Introduction to effective areas',['../md_extra__doc_230__effective__area.html#autotoc_md47',1,'']]],
  ['to_20measurements_15',['Matching PMT to Measurements',['../md_extra__doc_22__technicalities.html#autotoc_md38',1,'']]],
  ['to_20photons_16',['Making other volumes sensitive to photons',['../md_extra__doc_20__common.html#autotoc_md18',1,'']]],
  ['todo_20list_17',['Todo List',['../todo.html',1,'']]],
  ['token_18',['Token',['../struct_c_a_d_mesh_1_1_file_1_1_token.html',1,'CADMesh::File']]],
  ['tools_19',['tools',['../md_extra__doc_21__multithreading.html#autotoc_md29',1,'1. Use Valgrind Tools'],['../namespace_tools.html',1,'Tools']]],
  ['tools_20namespace_20',['The Tools namespace',['../md_extra__doc_22__technicalities.html#autotoc_md34',1,'']]],
  ['totalcrosssection_21',['totalcrosssection',['../class_o_m_sim_i_b_d.html#aad2e0e4a3f6501f4d2c3fb896b032ade',1,'OMSimIBD::totalCrossSection()'],['../class_o_m_sim_e_n_e_s.html#af2e3aedc5ca2d1006891540c0d038eb7',1,'OMSimENES::totalCrossSection()']]],
  ['tracking_22',['Non-terminating sensitive volumes for photon tracking',['../md_extra__doc_20__common.html#autotoc_md19',1,'']]],
  ['tracklength_23',['trackLength',['../struct_photon_info.html#ab4de62ab2d0c39d43c7d85f0fd995745',1,'PhotonInfo']]],
  ['transit_20time_20and_20detection_20probability_24',['PMTs Charge, transit time and detection probability',['../md_extra__doc_20__common.html#autotoc_md15',1,'']]],
  ['transit_20time_20scans_25',['Step 4: Matching gain / transit time scans',['../md_extra__doc_22__technicalities.html#autotoc_md42',1,'']]],
  ['transittime_26',['transitTime',['../struct_o_m_sim_p_m_t_response_1_1_p_m_t_pulse.html#a842337fbd6979ff70f1b5ab67ca52493',1,'OMSimPMTResponse::PMTPulse']]],
  ['troubleshooting_27',['Troubleshooting',['../index.html#autotoc_md71',1,'']]],
  ['troubleshooting_20multi_20threading_20issues_28',['Troubleshooting Multi-threading Issues',['../md_extra__doc_21__multithreading.html#autotoc_md28',1,'']]],
  ['types_29',['Special Material Types',['../md_extra__doc_20__common.html#autotoc_md5',1,'']]]
];
